services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: db_supersecurepassword
    volumes:
      - ./docker/n8n-V2/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:next
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_SCHEMA: n8n
      DB_POSTGRESDB_PASSWORD: db_supersecurepassword
    depends_on:
      - postgres
    volumes:
      - ./docker/n8n-V2/data:/home/node/.n8n
    restart: unless-stopped
